language: go
go:
  - 1.8
  - release
  - tip
install:
  # Add Godeps dependencies to GOPATH and PATH
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/flosch/pongo2
  - dep ensure
script:
  - go test -v
