language: go
os:
    - linux
    - osx
    - windows
go:
    - tip
install:
    - go get -u github.com/golang/dep/cmd/dep
    - go get github.com/flosch/pongo2
    - dep ensure
script:
    - go test -v
