host: 127.0.0.1:8081
context: /
use_tokens: true
commands:
  - name: echo
    command: /bin/echo
    arg: true
  - name: whoami
    command: /usr/bin/whoami
    arg: false
tokens:
  - name: testuser
    token: 123456789
